<?php

/**
 * AutorisationParentaleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AutorisationParentaleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AutorisationParentaleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AutorisationParentale');
    }
}