<?php

/**
 * DeclarationPerteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DeclarationPerteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DeclarationPerteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DeclarationPerte');
    }
}