<?php

/**
 * DroitProfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DroitProfilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DroitProfilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DroitProfil');
    }
}