<?php

/**
 * DroitsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DroitsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DroitsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Droits');
    }
}