<?php

/**
 * FicheIndividuelleEtatCivilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FicheIndividuelleEtatCivilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FicheIndividuelleEtatCivilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FicheIndividuelleEtatCivil');
    }
}