<?php

/**
 * GroupeSanguinTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GroupeSanguinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GroupeSanguinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GroupeSanguin');
    }
}