<?php

/**
 * ImmatriculationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImmatriculationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImmatriculationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Immatriculation');
    }
}