<?php

/**
 * LaissezPasserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LaissezPasserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LaissezPasserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LaissezPasser');
    }
}