<?php

/**
 * PasseportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PasseportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PasseportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Passeport');
    }
}