<?php

/**
 * PieceJointTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PieceJointTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PieceJointTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PieceJoint');
    }
}