<?php

/**
 * RegimeMariageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegimeMariageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegimeMariageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RegimeMariage');
    }
}