<?php

/**
 * SessionTravailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SessionTravailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SessionTravailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SessionTravail');
    }
}