<?php

/**
 * SignatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SignatureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SignatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Signature');
    }
}