<?php

/**
 * SituationMatrimonialeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SituationMatrimonialeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SituationMatrimonialeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SituationMatrimoniale');
    }
}