<?php

/**
 * TypePieceIdentiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TypePieceIdentiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TypePieceIdentiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TypePieceIdentite');
    }
}